---
# 1. Cria a pasta ~/workspace/nome_empresa
- name: "Garantir diretório de workspace: {{ profile.workspace }}"
  file:
    path: "{{ ansible_env.HOME }}/{{ profile.workspace }}"
    state: directory
    mode: '0755'

# 2. Gera a chave SSH (ex: ~/.ssh/id_empresa)
- name: "Gerar chave SSH para: {{ profile.name }}"
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: "{{ ansible_env.HOME }}/.ssh/{{ profile.ssh_key }}"
    ssh_key_comment: "{{ profile.email }}"
  # O Ansible é inteligente: se a chave já existir, ele não sobrescreve a menos que force.

# 3. Cria o arquivo de configuração Git específico da empresa
# O SEGREDO ESTÁ AQUI: 'core.sshCommand'
- name: "Criar gitconfig parcial para: {{ profile.name }}"
  copy:
    dest: "{{ ansible_env.HOME }}/.gitconfigs_partials/{{ profile.name }}.gitconfig"
    content: |
      [user]
          email = {{ profile.email }}
          # Opcional: name = Seu Nome (Se quiser variar o nome também)
      
      [core]
          # Mágica: Quando nesta pasta, use ESSA chave específica, não a padrão
          sshCommand = "ssh -i ~/.ssh/{{ profile.ssh_key }} -F /dev/null"
    mode: '0644'